"""Config-as-code smoke tests for the static `deploy/openrc/` templates.

These are hand-editable reference files (copy to `/etc/init.d` and
`/etc/conf.d` on a real Alpine host) — NOT generated by a script, so there is
nothing to execute here. Instead this asserts on the actual shipped file
content: that all five service scripts exist, are valid `openrc-run` shape,
reference the correct `hivepilot` CLI subcommand/mode, that the matching
`conf.d/*.example` files exist and never contain a real-looking secret value
(only placeholders), and that every service sources the shared cross-service
env file (`shared.env.example`) — the fix for the env-silo bug where a var
(`IS_SANDBOX`) set on 2 of 3 relevant services left the 3rd (the one that
actually resumes an approval-gated pipeline) without it.
"""

from __future__ import annotations

import re
import stat
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OPENRC_DIR = REPO_ROOT / "deploy" / "openrc"
INITD_DIR = OPENRC_DIR / "init.d"
CONFD_DIR = OPENRC_DIR / "conf.d"

# Must be the literal first line of every conf.d/hivepilot-*.example file —
# sources /etc/hivepilot/shared.env, the fix for the env-silo bug (see
# deploy/openrc/README.md, "Env silos — read this").
SHARED_ENV_SOURCING_LINE = "[ -f /etc/hivepilot/shared.env ] && . /etc/hivepilot/shared.env"

# service name -> substring expected in its command_args (real CLI subcommand/mode)
EXPECTED_COMMAND_ARGS = {
    "hivepilot-api": "api serve",
    "hivepilot-scheduler": "schedule daemon",
    "hivepilot-telegram": "telegram start --mode polling",
    "hivepilot-slack": "slack start --mode socket",
    "hivepilot-discord": "discord start --mode gateway",
}

ALL_SERVICES = tuple(EXPECTED_COMMAND_ARGS)


def test_readme_exists():
    readme = OPENRC_DIR / "README.md"
    assert readme.is_file(), f"missing {readme}"
    content = readme.read_text()
    assert "outbound" in content.lower()
    assert "cwd=/" in content or "cwd = /" in content.lower()


def test_readme_documents_env_silos():
    content = (OPENRC_DIR / "README.md").read_text()
    assert "Env silos" in content
    # the concrete incident that motivated the shared.env pattern
    assert "IS_SANDBOX" in content
    assert "shared.env" in content
    assert SHARED_ENV_SOURCING_LINE in content


def test_all_five_init_scripts_exist_and_are_openrc_shape():
    for svc in ALL_SERVICES:
        path = INITD_DIR / svc
        assert path.is_file(), f"missing {path}"
        content = path.read_text()
        assert content.startswith("#!/sbin/openrc-run"), f"{svc} must start with the openrc shebang"
        assert 'supervisor="supervise-daemon"' in content, f"{svc} missing supervisor line"
        assert "depend()" in content, f"{svc} missing depend() block"


def test_init_scripts_reference_correct_cli_subcommand_and_mode():
    for svc, expected in EXPECTED_COMMAND_ARGS.items():
        content = (INITD_DIR / svc).read_text()
        match = re.search(r'command_args="([^"]*)"', content)
        assert match, f'{svc} has no command_args="..." line'
        assert expected in match.group(1), (
            f"{svc} command_args={match.group(1)!r} does not contain expected {expected!r}"
        )


def test_init_scripts_are_executable():
    for svc in ALL_SERVICES:
        mode = stat.S_IMODE((INITD_DIR / svc).stat().st_mode)
        assert mode & stat.S_IXUSR, f"{svc} init.d script is not executable"


def test_scheduler_and_bot_services_depend_on_api():
    for svc in (
        "hivepilot-scheduler",
        "hivepilot-telegram",
        "hivepilot-slack",
        "hivepilot-discord",
    ):
        content = (INITD_DIR / svc).read_text()
        assert "after hivepilot-api" in content, f"{svc} should start after hivepilot-api"


def test_matching_conf_d_example_files_exist():
    for svc in ALL_SERVICES:
        path = CONFD_DIR / f"{svc}.example"
        assert path.is_file(), f"missing {path}"


def test_shared_env_example_exists():
    path = CONFD_DIR / "shared.env.example"
    assert path.is_file(), f"missing {path}"
    content = path.read_text()
    assert "IS_SANDBOX" in content
    assert "HIVEPILOT_CLAUDE_CAPTURE_USAGE" in content
    # shared.env.example must not actively source itself (mentioning the
    # sourcing line in an explanatory comment is fine and expected).
    assert content.splitlines()[0] != SHARED_ENV_SOURCING_LINE


def test_every_conf_d_hivepilot_example_starts_with_shared_env_sourcing_line():
    for svc in ALL_SERVICES:
        path = CONFD_DIR / f"{svc}.example"
        first_line = path.read_text().splitlines()[0]
        assert first_line == SHARED_ENV_SOURCING_LINE, (
            f"{path} must start with the shared.env sourcing line, got {first_line!r}"
        )


def test_slack_conf_example_documents_bot_and_app_token():
    content = (CONFD_DIR / "hivepilot-slack.example").read_text()
    assert "HIVEPILOT_SLACK_BOT_TOKEN" in content
    assert "HIVEPILOT_SLACK_APP_TOKEN" in content
    assert "HIVEPILOT_SLACK_SIGNING_SECRET" in content


def test_discord_conf_example_documents_bot_token():
    content = (CONFD_DIR / "hivepilot-discord.example").read_text()
    assert "HIVEPILOT_DISCORD_BOT_TOKEN" in content
    # public key is webhook-mode only, not gateway -- must be present but
    # clearly marked optional/commented, never required for the default mode.
    assert "HIVEPILOT_DISCORD_PUBLIC_KEY" in content


def test_scheduler_conf_example_documents_run_token():
    content = (CONFD_DIR / "hivepilot-scheduler.example").read_text()
    assert "HIVEPILOT_API_TOKEN" in content


# ---------------------------------------------------------------------------
# Never ship a real-looking secret in a committed example file.
# ---------------------------------------------------------------------------

_SUSPICIOUS_SECRET_PATTERNS = (
    re.compile(r"xox[baprs]-[0-9A-Za-z-]{10,}"),  # real Slack token shape
    re.compile(r"xapp-[0-9A-Za-z-]{10,}"),  # real Slack app token shape
    re.compile(r"\b\d{17,20}\.[\w-]{6,}\.[\w-]{20,}\b"),  # real Discord bot token shape
)


def test_conf_d_examples_contain_no_real_looking_secrets():
    for path in CONFD_DIR.glob("*.example"):
        content = path.read_text()
        for pattern in _SUSPICIOUS_SECRET_PATTERNS:
            assert not pattern.search(content), f"{path} looks like it contains a real secret"
