"""Config-as-code smoke tests for the static `deploy/systemd/` templates.

These are hand-editable reference unit files (copy to `/etc/systemd/system` on
a real Debian/Ubuntu host) — NOT generated by a script, so there is nothing to
execute here. Instead this asserts on the actual shipped file content: that
all five unit files exist, are valid `.service` shape, reference the correct
`hivepilot` CLI subcommand/mode (mirroring `deploy/openrc/init.d/*` exactly —
see `tests/test_deploy_openrc_templates.py`), that the matching
`env/hivepilot-<svc>.env.example` files exist and never contain a
real-looking secret value (only placeholders), that every service loads the
shared cross-service env file (`env/shared.env.example` — the systemd
equivalent of the OpenRC env-silo fix for `IS_SANDBOX`), and that the env
examples never use `export ` (systemd `EnvironmentFile=` does not run a
shell — `export `/`$VAR` expansion silently does nothing there).
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SYSTEMD_DIR = REPO_ROOT / "deploy" / "systemd"
ENV_DIR = SYSTEMD_DIR / "env"

# service name -> substring expected in its ExecStart (real CLI subcommand/mode),
# verified against deploy/openrc/init.d/* command_args -- must stay identical.
EXPECTED_EXEC_START = {
    "hivepilot-api": "api serve",
    "hivepilot-scheduler": "schedule daemon",
    "hivepilot-telegram": "telegram start --mode polling",
    "hivepilot-slack": "slack start --mode socket",
    "hivepilot-discord": "discord start --mode gateway",
}

ALL_SERVICES = tuple(EXPECTED_EXEC_START)

# services that must start after hivepilot-api, mirroring OpenRC's
# `depend() { after hivepilot-api; }` on hivepilot-scheduler/-telegram/-slack/-discord
DEPENDS_ON_API = (
    "hivepilot-scheduler",
    "hivepilot-telegram",
    "hivepilot-slack",
    "hivepilot-discord",
)


def _unit_path(svc: str) -> Path:
    return SYSTEMD_DIR / f"{svc}.service"


def _env_example_path(svc: str) -> Path:
    return ENV_DIR / f"{svc}.env.example"


def test_readme_exists():
    readme = SYSTEMD_DIR / "README.md"
    assert readme.is_file(), f"missing {readme}"
    content = readme.read_text()
    assert "journalctl" in content
    assert "EnvironmentFile" in content


def test_readme_documents_environmentfile_shell_trap():
    content = (SYSTEMD_DIR / "README.md").read_text()
    # systemd EnvironmentFile does NOT run a shell -- export/expansion is a trap
    assert "does not run a shell" in content.lower() or "does not run a shell" in content
    assert "KEY=value" in content or "KEY=VALUE" in content.upper()


def test_readme_documents_path_and_troubleshooting():
    content = (SYSTEMD_DIR / "README.md").read_text()
    assert "journalctl -u" in content
    assert "PATH" in content
    assert "slack-bolt" in content or "discord.py" in content


def test_all_five_unit_files_exist_and_are_systemd_shape():
    for svc in ALL_SERVICES:
        path = _unit_path(svc)
        assert path.is_file(), f"missing {path}"
        content = path.read_text()
        assert "[Unit]" in content
        assert "[Service]" in content
        assert "[Install]" in content
        assert "Type=simple" in content
        assert "Restart=always" in content
        assert "RestartSec=" in content


def test_units_reference_correct_cli_subcommand_and_mode():
    for svc, expected in EXPECTED_EXEC_START.items():
        content = _unit_path(svc).read_text()
        match = re.search(r"^ExecStart=(.*)$", content, re.MULTILINE)
        assert match, f"{svc} has no ExecStart= line"
        assert "/opt/hivepilot/venv/bin/hivepilot" in match.group(1)
        assert expected in match.group(1), (
            f"{svc} ExecStart={match.group(1)!r} does not contain expected {expected!r}"
        )


def test_units_use_optional_environmentfile_for_shared_and_service_env():
    for svc in ALL_SERVICES:
        content = _unit_path(svc).read_text()
        assert "EnvironmentFile=-/etc/hivepilot/shared.env" in content, (
            f"{svc} must load the shared env file with the optional-file dash prefix"
        )
        assert f"EnvironmentFile=-/etc/hivepilot/{svc}.env" in content, (
            f"{svc} must load its own env file with the optional-file dash prefix"
        )


def test_units_set_working_directory_root_with_explanation():
    for svc in ALL_SERVICES:
        content = _unit_path(svc).read_text()
        assert "WorkingDirectory=/" in content
        # must explain the cwd=/ env-silo trap, mirroring the OpenRC lesson
        assert "cwd" in content.lower() or "absolute" in content.lower()


def test_dependent_services_depend_on_api():
    for svc in DEPENDS_ON_API:
        content = _unit_path(svc).read_text()
        after_lines = [line for line in content.splitlines() if line.strip().startswith("After=")]
        assert any("hivepilot-api.service" in line for line in after_lines), (
            f"{svc} should start after hivepilot-api"
        )


def test_units_have_hardening_block_with_documented_exceptions():
    for svc in ALL_SERVICES:
        content = _unit_path(svc).read_text()
        assert "NoNewPrivileges=yes" in content
        # ProtectHome/ReadOnlyPaths/PrivateTmp must be explicitly commented on
        # WHY they are not enabled -- agents write into repos/vault/tmp.
        assert "ProtectHome" in content
        assert "PrivateTmp" in content


def test_units_document_root_is_sandbox_nuance():
    for svc in ALL_SERVICES:
        content = _unit_path(svc).read_text()
        assert "IS_SANDBOX" in content
        assert "User=" in content or "non-root" in content.lower()


def test_units_are_ini_parseable_key_value_pairs():
    for svc in ALL_SERVICES:
        content = _unit_path(svc).read_text()
        # crude but effective: every non-comment, non-section, non-blank line
        # must look like Key=Value (systemd unit file grammar).
        for line in content.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or stripped.startswith("["):
                continue
            assert "=" in stripped, f"{svc}: malformed line {stripped!r}"


def test_matching_env_example_files_exist():
    for svc in ALL_SERVICES:
        path = _env_example_path(svc)
        assert path.is_file(), f"missing {path}"


def test_shared_env_example_exists():
    path = ENV_DIR / "shared.env.example"
    assert path.is_file(), f"missing {path}"
    content = path.read_text()
    assert "IS_SANDBOX" in content


def test_env_examples_never_use_export_or_shell_syntax():
    all_env_files = list(ENV_DIR.glob("*.env.example"))
    assert all_env_files, "no env examples found"
    for path in all_env_files:
        content = path.read_text()
        for line in content.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            assert not stripped.startswith("export "), (
                f"{path} line {stripped!r} uses shell 'export' -- systemd "
                "EnvironmentFile does not run a shell, this silently does nothing"
            )
            # KEY=value, no $VAR expansion (systemd EnvironmentFile is literal)
            assert re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", stripped), (
                f"{path} line {stripped!r} is not a plain KEY=value pair"
            )


def test_slack_env_example_documents_bot_and_app_token():
    content = _env_example_path("hivepilot-slack").read_text()
    assert "HIVEPILOT_SLACK_BOT_TOKEN" in content
    assert "HIVEPILOT_SLACK_APP_TOKEN" in content
    assert "HIVEPILOT_SLACK_SIGNING_SECRET" in content


def test_discord_env_example_documents_bot_token():
    content = _env_example_path("hivepilot-discord").read_text()
    assert "HIVEPILOT_DISCORD_BOT_TOKEN" in content


def test_scheduler_env_example_documents_run_token():
    content = _env_example_path("hivepilot-scheduler").read_text()
    assert "HIVEPILOT_API_TOKEN" in content


# ---------------------------------------------------------------------------
# Never ship a real-looking secret in a committed example file.
# ---------------------------------------------------------------------------

_SUSPICIOUS_SECRET_PATTERNS = (
    re.compile(r"xox[baprs]-[0-9A-Za-z-]{10,}"),  # real Slack token shape
    re.compile(r"xapp-[0-9A-Za-z-]{10,}"),  # real Slack app token shape
    re.compile(r"\b\d{17,20}\.[\w-]{6,}\.[\w-]{20,}\b"),  # real Discord bot token shape
)


def test_env_examples_contain_no_real_looking_secrets():
    for path in ENV_DIR.glob("*.env.example"):
        content = path.read_text()
        for pattern in _SUSPICIOUS_SECRET_PATTERNS:
            assert not pattern.search(content), f"{path} looks like it contains a real secret"
